NotifierWebsite/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.views.generic.base import RedirectView
from NotifierWebsite.views import LetsEncrypt, ManifestJson

urlpatterns = [
    url(r'', include('ncsumn.urls')),

    url(regex=r'^admin/',
        view=admin.site.urls),

    url(regex=r'^%s$' % settings.SSL_URL,
        view=LetsEncrypt.as_view(),
        name='ssl'),

    url(regex=r'manifest.json/$',
        view=ManifestJson.as_view(),
        name='manifest'),

    url(regex=r'favicon.ico/$',
        view=RedirectView.as_view(url=static('favicon.png'), permanent=True),
        name='favicon'),
]

ncsumn/urls.py
from django.conf.urls import url
from ncsumn import views, api_views

urlpatterns = [
    # Regular views
    url(regex=r'^$',
        view=views.Home.as_view(),
        name='home'),

    url(regex=r'^confirm/$',
        view=views.Confirm.as_view(),
        name='confirm'),

    url(regex=r'^prefs/$',
        view=views.Prefs.as_view(),
        name='prefs'),

    url(regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'),

    url(regex=r'^about/$',
        view=views.About.as_view(),
        name='about'),

    url(regex=r'^changelog/$',
        view=views.ChangeLog.as_view(),
        name='changelog'),

    # API views
    url(regex=r'^sms/$',
        view=api_views.SMSResponse.as_view(),
        name='sms'),

    url(regex=r'^notifierusers/(?P<phone_number>\+1[0-9]{10})/$',
        view=api_views.NotifierUserAPI.as_view(),
        name='notifierusers'),

    url(regex=r'tag_release/$',
        view=api_views.TagRelease.as_view(),
        name='tag_release'),
]

ncsumn/forms.py
from django import forms
from ncsumn.models import MenuItem, NotifierUser, DiningHall, Meal
from django.core.validators import RegexValidator
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from ncsumn.utils import send_twilio_message
from django.utils.crypto import get_random_string


class SignupForm(forms.Form):
    phone_regex = RegexValidator(regex=r'^\d{9,15}$', message="Phone number must be entered in the format: '99999999'.")
    phone_number = forms.CharField(validators=[phone_regex], help_text="(e.g. 9195152011)", max_length=10)
    favorite_dish = forms.ModelChoiceField(queryset=MenuItem.objects.all().order_by('name'),
                                           help_text="Dishes with check marks are being served today.")


NOT_VERIFIED_ERROR = "Your phone hasn't been verified yet."
NO_PHONE_ERROR = "Your phone number is not in the system. You need to sign up first."
INVALID_ERROR = "Phone number must be entered in the format: '99999999'."
BAD_CODE = "The code you entered was invalid."


class LoginForm(AuthenticationForm):
    phone_regex = RegexValidator(regex=r'^\d{9,15}$', message=INVALID_ERROR)
    # The username is the phone number without the country code
    username = forms.CharField(
        validators=[phone_regex], help_text="(e.g. 9195152011)", max_length=10,
        widget=forms.TextInput(attrs={'placeholder': 'Phone Number'})
    )
    # The password is their verification code
    password = forms.CharField(
        max_length=6, required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Code'})
    )

    def clean_username(self):
        """
        The phone number must correspond to an existing, verified NotifierUser
        """
        number = "+1" + self.cleaned_data['username']
        try:
            user = NotifierUser.objects.get(phone_number=number)
            if not user.verified:
                raise forms.ValidationError(NOT_VERIFIED_ERROR)
        except ObjectDoesNotExist:
            raise forms.ValidationError(NO_PHONE_ERROR)
        return number

    def clean(self):
        """
        If both fields are valid, try to login the user.
        If code is blank, send a text.
        """
        phone_number = self.cleaned_data.get('username')
        code = self.cleaned_data.get('password')
        if phone_number is not None and code:
            # Try to log in
            self.user_cache = authenticate(username=phone_number, password=code)
            if self.user_cache is None:
                raise forms.ValidationError(
                    BAD_CODE,
                    code='invalid_login',
                    params={'username': phone_number},
                )
            else:
                self.confirm_login_allowed(self.user_cache)
        elif phone_number:
            # Set the user's password to a random code and text them that code
            notifieruser = NotifierUser.objects.get(phone_number=phone_number)
            code = get_random_string(6, 'bcdfghjkmnpqrstvwxz123456789')
            notifieruser.auth_user.set_password(code)
            notifieruser.auth_user.save()
            notifieruser.save()
            msg = "ncsu-mn: Your verification code is %s" % code
            send_twilio_message(notifieruser, msg)

        return self.cleaned_data


class PrefsForm(forms.Form):
    locations = forms.ModelMultipleChoiceField(
        queryset=DiningHall.objects.all().order_by('name'),
        label="Dining halls you care about",
        help_text=("You can specify which dining halls you want to be notified about. For example, "
                   "if they serve one of your favorite foods at Clark, but you have Clark "
                   "unchecked, we won't text you about it."),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    meals = forms.ModelMultipleChoiceField(
        queryset=Meal.objects.all().order_by('name'),
        label="Meals you care about",
        help_text=("If you're a late riser, you probably should uncheck \"Breakfast\"."),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    wants_updates = forms.BooleanField(
        label="I want to know when ncsu-mn gets updated",
        help_text=("If this box is checked and the site gets updated, we'll add a short message "
                   "to the end of one of your normal notifications which tells you about new features."),
        required=False,
    )
    cares_about_summer = forms.BooleanField(
        label="I want to keep recieving notifications over the summer",
        help_text=("If you use the dining halls over the summer, you might want to check this box."),
        required=False,
    )
    add_dish = forms.ModelChoiceField(
        label="Add a new dish",
        help_text=("We'll text you when they're serving this dish (as well as any of your "
                   "existing dishes) at one of your speicifed dining halls."),
        queryset=MenuItem.objects.all().order_by('name'),
        required=False
    )
    # Dishes are deleted asynchronously via the API view

ncsumn/views.py
from django.views.generic import FormView, TemplateView
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from ncsumn.forms import (SignupForm, LoginForm, PrefsForm)
from ncsumn.models import NotifierUser, DiningHall, Meal
from ncsumn.utils import send_twilio_message


class Home(FormView):
    template_name = 'home.html'
    form_class = SignupForm
    title = "Signup - NCSU Menu Notifier"

    def get(self, request):
        # Send the user to prefs if they're already logged in (to save $$$)
        if request.user.is_authenticated() and not request.user.is_staff:
            return HttpResponseRedirect(reverse('prefs'))
        else:
            return super(Home, self).get(request)

    def get_success_url(self):
        return reverse('confirm')

    def form_valid(self, form):
        cd = form.cleaned_data
        # Create a new user if needed and add the food to their favorites
        full_number = "+1" + cd['phone_number']
        auth_user = User.objects.get_or_create(username=full_number)[0]
        user, was_created = NotifierUser.objects.get_or_create(phone_number=full_number, auth_user=auth_user)
        msg = "ncsu-mn: Are you sure you want to sign up for NCSU " \
              "menu notifications?\nReply 'Confirm' if so."
        if was_created:
            # Set their initial preferences
            user.fav_foods.add(cd['favorite_dish'])
            user.locations.add(*DiningHall.objects.all())
            user.meals.add(*Meal.objects.all())
            # Verify the user
            send_twilio_message(user, msg)
        else:
            if not user.verified:
                # Verify the user again, but add more info to the message
                send_twilio_message(user, msg + "\nIf you did not request this, you can reply STOP.")
                user.fav_foods.add(cd['favorite_dish'])
            else:
                messages.info(self.request, "You've already signed up. Please log in to configure your account.")
                return HttpResponseRedirect(reverse('login'))

        # Call the parent method to redirect to success_url
        return super(Home, self).form_valid(form)


class Confirm(TemplateView):
    template_name = 'confirm.html'
    title = "Confirm - NCSU Menu Notifier"


class About(TemplateView):
    template_name = 'about.html'
    title = "About - NCSU Menu Notifier"


class ChangeLog(TemplateView):
    template_name = 'changelog.html'
    title = "Changes - NCSU Menu Notifier"


class LoginView(FormView):
    """
    Lots of code copy/pasted from Django 2.0's class-based
    LoginView. form_invalid and form_valid are the only overrides
    """
    template_name = 'login.html'
    title = "Login - NCSU Menu Notifier"
    form_class = LoginForm
    redirect_authenticated_user = False

    def get_success_url(self):
        return reverse('prefs')

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.success_url
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        If there's no password (code), return "Sent" to show that a message
        was sent in the form's clean() method.
        Otherwise, log the user in.
        """
        if form.cleaned_data.get('password'):
            auth_login(self.request, form.get_user())
            return HttpResponseRedirect(self.get_success_url())
        else:
            # Pretend like the 'username' field has an error so the JS can render it
            return JsonResponse({'username': 'Sent'})

    def form_invalid(self, form):
        """
        Need custom behavior for async form validation
        """
        # Only return json when the error is in the username
        return JsonResponse(form.errors)


@method_decorator(login_required, name='dispatch')
class Prefs(FormView):
    template_name = 'prefs.html'
    title = "User Preferences - NCSU Menu Notifier"
    form_class = PrefsForm

    def get_success_url(self):
        return reverse('prefs')

    def get_context_data(self, **kwargs):
        """Put all the user's foods in the context"""
        notifier_user = NotifierUser.objects.get(phone_number=self.request.user.username)
        kwargs = super(Prefs, self).get_context_data(**kwargs)
        kwargs['fav_foods'] = notifier_user.fav_foods.all()
        return kwargs

    def get_initial(self):
        """
        Set the user's initial locations and meals
        """
        notifier_user = NotifierUser.objects.get(phone_number=self.request.user.username)
        initial_vals = {
            'locations': [l.id for l in notifier_user.locations.all()],
            'meals': [m.id for m in notifier_user.meals.all()],
            'wants_updates': notifier_user.wants_updates,
            'cares_about_summer': notifier_user.cares_about_summer
        }
        return initial_vals

    def form_valid(self, form):
        cd = form.cleaned_data
        phone_number = self.request.user.username
        notifier_user = NotifierUser.objects.get(phone_number=phone_number)

        # Add any dish they want to add
        dish_to_add = cd.get('add_dish')
        if dish_to_add:
            notifier_user.fav_foods.add(dish_to_add)

        # Change their prefered locations
        updated_locations = cd.get('locations')
        notifier_user.locations.clear()
        for loc in updated_locations:
            notifier_user.locations.add(loc)

        # Change their prefered meals
        updated_meals = cd.get('meals')
        notifier_user.meals.clear()
        for meal in updated_meals:
            notifier_user.meals.add(meal)

        # Change their other preferences
        notifier_user.wants_updates = cd.get('wants_updates')
        notifier_user.cares_about_summer = cd.get('cares_about_summer')

        notifier_user.save()

        return super(Prefs, self).form_valid(form)

ncsumn/templates/about.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<div class="container centered">
    <div class="central-square">
        <div class="prefs-header">
            <h3 class="compact-header">About</h3>
            <span class="label label-info text-right">NCSU Menu Notifier</span>
        </div>
        <div>
            <h4 class="text-bold">What is it?</h4>
                <div class="centered">
                  <p>
                      The NCSU Menu Notifier is a web app that will automatically notify you via SMS
                      when your favorite foods are being served at Fountain, Clark, or Case dining halls. Like this:
                  </p>
                  <img class="img-responsive" src="{% static 'phone_screenshot_cropped.png' %}" alt="Screenshot of a text message">
                </div>
            <br/>
            <h4 class="text-bold">How do I use it?</h4>
                <p>
                    <span class="text-bold">First time users:</span> On the <a href="{% url 'home' %}">home page</a>,
                    put in your 10-digit phone number (no parentheses or dashes required) and pick your favorite
                    dish from the dropdown. You will be sent a text to verify your phone number.
                    You can add more dishes and fine-tune your notifications on the <a href="{% url 'prefs' %}">preferences page</a>.
                </p>
                <p>
                    <span class="text-bold">Returning users:</span> You can access your account preferences <a href="{% url 'prefs' %}">here</a>.
                    There, you can change which meals and which dining halls you want to be notified about.
                    You can also add and remove multiple dishes to your account.
                </p>
            <br/>
            <h4 class="text-bold">How does it work under the hood?</h4>
                <p>
                    This website uses the <a href="https://www.djangoproject.com/">Django Web Framework</a>,
                    a popular Python framework for websites used by Pinterest, Instagram, and many others.
                </p>
                <p>
                    The menu is updated every day by using a custom Python web scraper
                    and a package called <a href="https://pypi.python.org/pypi/beautifulsoup4">beautifulsoup</a>.
                    Each dish is then saved in a PostgreSQL database.
                </p>
                <p>
                    Text messages are sent by using <a href="https://www.twilio.com/">Twilio's</a> API,
                    which is the same API used by Uber to programmatically send text messages when
                    your Uber driver has arrived.
                </p>
                <p>
                  The site and the database is hosted on <a href="https://www.heroku.com/platform">Heroku</a>,
                  and the code repository is hosted on <a href="https://about.gitlab.com/">GitLab</a>. GitLab also
                  provides a <a href="https://en.wikipedia.org/wiki/Continuous_integration">continuous integration</a>
                  server for this site.
                </p>
            <br/>
            <h4 class="text-bold">How do I stop receiving texts?</h4>
                <p>
                  If you text "STOP" to this site's phone number, then Twilio will step in and prevent all
                  of ncsu-mn's messages from reaching you until you reply "START". But that's kind of a nuclear option, so the other
                  option is to just remove all your favorite foods from your account on your
                  <a href="{% url 'prefs' %}">preferences page</a>.
                </p>
        </div>
    </div>
</div>
{% endblock %}

ncsumn/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{{view.title}}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#cc0000">
    <meta name="description" content="Get notified when your favorite foods are being served at the NCSU dining hall." />
    <title>NCSU Menu Notifier</title>
    <!-- Progressive Web App Manifest -->
    <link rel="manifest" href="/manifest.json">
    <!-- jQuery and jQuery plugins -->
    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'chosen/chosen.jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'chosen/chosen.min.css' %}">

    <!-- NCSU Bootstrap JS -->
    <script src="https://cdn.ncsu.edu/brand-assets/bootstrap/js/bootstrap.min.js"></script>

    <!-- NCSU Bootstrap CSS -->
    <link href="https://cdn.ncsu.edu/brand-assets/bootstrap/css/bootstrap.css"
    rel="stylesheet" media="screen" type="text/css" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'custom/stylesheets/all.css' %}"/>

    <!-- Favicon -->
    <link rel="shortcut icon"
      type="image/x-icon"
      src="{% static 'favicon.ico' %}"/>


</head>
<script>
// Create a Service Worker to run in the background of progressive web apps
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function() {
    navigator.serviceWorker.register("{% static 'custom/serviceWorker.js' %}").then(function(registration) {
      // Registration was successful
    }).catch(function(err) {
      // Registration failed
      console.log('ServiceWorker registration failed: ', err);
    });
  });
}
</script>
<body>
{% block content %}
{% endblock %}
</body>
<footer>
{% include "footer.html" %}
</footer>
</html>

ncsumn/templates/changelog.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}

<div class="container centered">
  <div class="central-square">
    {% load tags %}
    {% render_changelog %}
  </div>
</div>

{% endblock %}

ncsumn/templates/confirm.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="container centered">
    <div class="central-circle centered">
        <div class="circle-div centered">
            <h3 class="text-center compact-header">
                Confirm
            </h3>
            {% bootstrap_messages %}
            <p class="text-center">
                We sent a text to your phone number.
            </p>
            <p class="text-center">
                Please confirm your identity
            </p>
            <p class="text-center">
                by replying to that text.
            </p>
            <br/>
            <p class="text-center text-muted">
                After confirming, you can <a href="{% url 'login' %}">log in</a>.
            </p>
        </div>
    </div>
</div>
{% endblock %}

ncsumn/templates/footer.html
<a class="text-center" href="{% url 'about' %}">About</a>
<div class="separator"></div>
<a class="text-center" href="{% url 'changelog' %}">Change Log</a>
<div class="separator"></div>
<a class="text-center" href="https://gitlab.com/mac-chaffee/ncsu-menu-notifier">See the Code</a>
<div class="separator"></div>
<a class="text-center" href="mailto:bugs@ncsu-mn.com?subject=Bug Report">Report a Bug</a>

ncsumn/templates/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<div class="container centered">
    <div class="central-circle centered">
        <h3 class="text-center circle-header">
            Free NCSU Menu Notifications
        </h3>
        {% bootstrap_messages %}
        {% bootstrap_form_errors form %}
        <!-- Form goes here -->
        <div class="circle-form">
            <form action="" method="POST" novalidate>
                {% csrf_token %}
                {% bootstrap_field form.phone_number %}
                {% bootstrap_field form.favorite_dish %}
                {% bootstrap_button "Sign me up!" button_type="submit" button_class="btn-primary btn-block" %}
            </form>
        </div>
        <div class="extra-info">
                <span>Been here before? <a href="/login">Log in</a></span>
        </div>
    </div>
</div>
<script>
$("#id_favorite_dish").chosen();
</script>
{% endblock %}

ncsumn/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content %}

<div class="container centered">
    <div class="central-circle centered">
        <h3 class="text-center login-header">
            Login
        </h3>
        {% bootstrap_messages %}
        {% bootstrap_form_errors form %}
        <!-- Form goes here -->
        <div class="circle-form">
            <form id="login-form" action="" method="POST">
                {% csrf_token %}
                {% bootstrap_field form.username show_label=False %}
                <div class="centered">
                  <button id="send-code" class="btn btn-primary btn-block" type="submit"
                          data-toggle="collapse" data-target="#code-receiver">Send code</button>
                </div>
                <div id="code-receiver" class="collapse">
                    {% bootstrap_field form.password show_label=False %}
                    {% bootstrap_button "Verify" button_type="submit" button_class="btn-primary btn-block" %}
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{% static 'custom/login.js' %}"></script>
{% endblock %}

ncsumn/templates/prefs.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<div class="container centered">
  <div class="central-square">

    <div class="prefs-header">
      <h3 class="compact-header">Preferences</h3>
      <a class="label label-info text-right" href="{% url 'notifierusers' phone_number=user %}">{{user}}</a>
      {% bootstrap_messages %}
      {% bootstrap_form_errors form %}
    </div>
    <label class="control-label">Your favorite foods</label>
    <form id="prefs-form" action="" method="POST">
      {% csrf_token %}
      <ul class="list-group">
        {% for food in fav_foods %}
          <li id="food-item-{{food.id}}" class="list-group-item justify-content-between">
            {{food.name}}
            <button data-id="{{food.id}}" class="btn btn-danger btn-xs del-dish-button" type="button">Remove</button>
          </li>
        {% endfor %}
        {% if not fav_foods %}
        <li class="list-group-item">
          You don't have any. You can add new favorite foods below.
        </li>
        {% endif %}
        <li class="list-group-item">
          {% bootstrap_field form.add_dish %}
          <div id="save-button-add" class="save-button">
            <button class="btn btn-info" type="submit">Save</button>
          </div>
        </li>
      </ul>

      {% bootstrap_field form.locations %}
      <div id="save-button-locations" class="save-button">
        <button class="btn btn-info" type="submit">Save</button>
      </div>

      {% bootstrap_field form.meals %}
      <div id="save-button-meals" class="save-button">
        <button class="btn btn-info" type="submit">Save</button>
      </div>

      <label class="control-label">Other settings</label>
      {% bootstrap_field form.cares_about_summer %}
      {% bootstrap_field form.wants_updates %}
      <div id="save-button-updates" class="save-button">
        <button class="btn btn-info" type="submit">Save</button>
      </div>
    </form>
  </div>
</div>
<script src="{% static 'custom/prefs.js' %}"></script>
<script>
// Add the CSRF token to the ajax headers
$.ajaxSetup({
  beforeSend: function(xhr, settings) {
    xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
  }
});

// Make AJAX calls to the NotifierUser API view to delete dishes when the buttons are clicked
$(".del-dish-button").click( function() {
  var food_to_delete = $(this).data("id");
  var patch_data = {"op": "remove", "id": food_to_delete};
  // Change the button to a loading icon
  $(this).replaceWith("<div class='loading-pulse'></div>");
  $.ajax({
    url: "{% url 'notifierusers' phone_number=request.user.username %}",
    type: "PATCH",
    data: patch_data,
    success: function(response) {
      // Remove that row of the table
      $(`#food-item-${food_to_delete}`).remove();
    },
  });
});

</script>
{% endblock %}